DELETE FROM votos WHERE id > 0;
DELETE FROM sessao_votos WHERE id > 0;
DELETE FROM associados WHERE id > 0;
DELETE FROM pautas WHERE id > 0;

ALTER TABLE associados ALTER COLUMN id RESTART WITH 1;
ALTER TABLE sessao_votos ALTER COLUMN id RESTART WITH 1;
ALTER TABLE votos ALTER COLUMN id RESTART WITH 1;
ALTER TABLE pautas ALTER COLUMN id RESTART WITH 1;